
USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE SCD_DEMO TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA SCD_DEMO.SCD2 TO ROLE SYSADMIN;


GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA SCD_DEMO.SCD2
TO ROLE SYSADMIN;

GRANT SELECT
ON ALL STREAMS IN SCHEMA SCD_DEMO.SCD2
TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SYSADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
